# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, default=None)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='When the eating event occurred or began.')),
                ('end', models.DateTimeField(blank=True, help_text='When provided, defines a duration of the eating event by subtracting the <code>Start</code> field.', null=True)),
                ('item', models.TextField(blank=True, help_text='Description of any item eaten.', null=True)),
                ('value', models.FloatField(blank=True, help_text='The recorded calories for the eating event.', null=True)),
                ('units', models.CharField(blank=True, choices=[('Cal', 'Cal')], help_text='Units associated with the <code>Value</code> field.', max_length=9, null=True)),
                ('alone', models.BooleanField(default=True, help_text='Whether metric event occurred while being alone.')),
                ('notes', models.TextField(blank=True, help_text='Any extra notes associated with metric event.', null=True)),
            ],
            options={
                'db_table': 'metric_eat',
            },
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='When the metric occurred or began.')),
                ('end', models.DateTimeField(help_text='When provided, defines a duration of the metric by subtracting the <code>start</code> field.')),
                ('alone', models.BooleanField(default=True, help_text='Whether metric event occurred while being alone.')),
                ('notes', models.TextField(blank=True, help_text='Any extra notes associated with metric event.', null=True)),
            ],
            options={
                'db_table': 'metric_sleep',
            },
        ),
    ]
