# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oolong_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(db_index=True, help_text='When the metric event occurred or began.')),
                ('type', models.CharField(choices=[('screen_time', 'Screen time'), ('steps', 'Steps')], db_index=True, help_text='The type of daily metric.', max_length=10)),
                ('value', models.FloatField(blank=True, db_index=True, help_text='The recorded value for the type of metric', null=True)),
                ('units', models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('steps', 'Steps'), ('hours', 'Hours')], db_index=True, help_text='Units associated with the <code>Value</code> field.', max_length=10, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='end',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When provided, defines a duration of the metric event by subtracting the <code>Time stamp</code> field.', null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('gym', 'Gym'), ('run', 'Run'), ('walk', 'Walk')], db_index=True, help_text='The type of exercise.', max_length=10),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='units',
            field=models.CharField(blank=True, choices=[('miles', 'Miles'), ('km', 'Kilometers')], db_index=True, help_text='Units associated with the <code>Value</code> field.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(db_index=True, default=None, help_text='Date on which question was answered.'),
        ),
    ]
