# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eat',
            name='units',
            field=models.CharField(blank=True, choices=[('Cal', 'Cal')], default='Cal', help_text='Units associated with the <code>Value</code> field.', max_length=9, null=True),
        ),
    ]
