# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eat',
            name='units',
            field=models.CharField(blank=True, choices=[('cal', 'Cal'), ('number', 'Number')], db_index=True, help_text='Units associated with the <code>Value</code> field.', max_length=10, null=True),
        ),
    ]
