# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relax',
            name='end',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When provided, defines a duration of the metric event by subtracting the <code>Time stamp</code> field.', null=True),
        ),
        migrations.AddField(
            model_name='relax',
            name='type',
            field=models.CharField(choices=[('read_book', 'Read book'), ('work', 'Work'), ('hobby', 'Hobby'), ('therapist', 'Therapist'), ('phone', 'Phone'), ('friends', 'Friends'), ('walk', 'Walk'), ('video_game', 'Video game'), ('meditation', 'Meditation'), ('walk', 'Walk'), ('other', 'Other')], db_index=True, default='other', help_text='The type of relax/social event.', max_length=10),
        ),
    ]
