# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0002_auto_20180228_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='When the metric occurred or began.')),
                ('item', models.CharField(choices=[('water', 'Water'), ('tea', 'Tea'), ('coffee', 'Coffee'), ('alcohol', 'Alcohol'), ('soda', 'Soda')], default='water', help_text='The type of item drunk.', max_length=9)),
                ('value', models.FloatField(blank=True, help_text='The recorded volume for the metric event.', null=True)),
                ('units', models.CharField(blank=True, choices=[('fl oz', 'Fluid Ounce')], help_text='Units associated with the <code>Value</code> field.', max_length=9, null=True)),
                ('has_caffeine', models.BooleanField(default=True, help_text='Whether the metric event contained caffeine.')),
                ('alone', models.BooleanField(default=True, help_text='Whether metric event occurred while being alone.')),
                ('notes', models.TextField(blank=True, help_text='Any extra notes associated with metric event.', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='eat',
            name='end',
            field=models.DateTimeField(blank=True, help_text='When provided, defines a duration of the metric event by subtracting the <code>Start</code> field.', null=True),
        ),
        migrations.AlterField(
            model_name='eat',
            name='start',
            field=models.DateTimeField(help_text='When the metric event occurred or began.'),
        ),
        migrations.AlterField(
            model_name='eat',
            name='units',
            field=models.CharField(blank=True, choices=[('cal', 'Cal')], help_text='Units associated with the <code>Value</code> field.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='eat',
            name='value',
            field=models.FloatField(blank=True, help_text='The recorded calories for the metric event.', null=True),
        ),
    ]
