# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0002_auto_20180306_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Date on which question was answered.'),
        ),
    ]
