# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0002_auto_20180307_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='mood',
            field=models.CharField(blank=True, choices=[('happy', 'Happy'), ('anxious', 'Anxious'), ('depressed', 'Depressed'), ('sad', 'Sad'), ('lonely', 'Lonely')], db_index=True, help_text='General mood of this note.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sleep',
            name='score',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_index=True, help_text='Generalized mood score waking up; high score is a good mood, low score is a bad/low mood.', max_length=1, null=True),
        ),
    ]
