# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0002_auto_20180228_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='form_header',
            field=models.TextField(help_text="Questionnaire form header help; e.g. 'Over the last 2 weeks, how often have you been bothered by the following problems?'", null=True),
        ),
    ]
