# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0002_auto_20180305_0014'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='relax',
            table='metric_relax',
        ),
    ]
