# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0003_auto_20180306_1407'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='daily',
            table='metric_daily',
        ),
        migrations.AlterModelTable(
            name='note',
            table='metric_note',
        ),
    ]
