# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0003_auto_20180228_0949'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='drink',
            table='metric_drink',
        ),
    ]
