# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0004_auto_20180308_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleep',
            name='score',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_index=True, default=3, help_text='Generalized mood score while waking up; <b>high</b> score is a <code>good</code> mood, <b>low</b> score is a <code>bad/low</code> mood.', max_length=1),
        ),
    ]
