# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0009_auto_20180309_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relax',
            name='type',
            field=models.CharField(choices=[('read_book', 'Read book'), ('work', 'Work'), ('hobby', 'Hobby'), ('therapist', 'Therapist'), ('phone', 'Phone'), ('friends', 'Friends'), ('video_game', 'Video game'), ('meditation', 'Meditation'), ('internet', 'Internet'), ('television', 'Television'), ('other', 'Other')], db_index=True, help_text='The type of relax/social event.', max_length=15),
        ),
    ]
