# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0011_exercise_mood_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotResponse',
            fields=[
                ('date', models.TextField(primary_key=True, serialize=False)),
                ('epoch', models.IntegerField()),
                ('avg', models.FloatField()),
                ('std', models.FloatField()),
            ],
            options={
                'db_table': 'plot_response',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='label',
            field=models.TextField(db_index=True, help_text='Label displayed on button used for navigation.', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.TextField(db_index=True, help_text='Corresponding model name; must exist as a Django model.'),
        ),
    ]
