# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0017_questionnaire_default_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='score',
            field=models.IntegerField(db_index=True, default=0, help_text='Score for given response; e.g. 4.'),
            preserve_default=False,
        ),
    ]
