# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0018_response_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.ForeignKey(db_index=False, help_text='Response to given question.', on_delete=django.db.models.deletion.CASCADE, to='oolong_app.AvailableResponse'),
        ),
    ]
