# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0021_auto_20180331_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='response',
        ),
    ]
