# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0023_auto_20180401_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotDrink',
            fields=[
                ('date', models.TextField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('epoch', models.IntegerField()),
                ('fl_oz', models.FloatField()),
            ],
            options={
                'db_table': 'plot_drink',
                'managed': False,
            },
        ),
    ]
