# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oolong_app', '0025_auto_20180411_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='time_stamp',
            field=models.DateTimeField(db_index=True, help_text='When the metric event occurred or began.'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='time_stamp',
            field=models.DateTimeField(db_index=True, help_text='When the metric event occurred or began.'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='time_stamp',
            field=models.DateTimeField(db_index=True, help_text='When the metric event occurred or began.'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='units',
            field=models.CharField(choices=[('fl oz', 'Fluid Ounce'), ('ml', 'Milliliter')], db_index=True, help_text='Units associated with the <code>Value</code> field.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='volume',
            field=models.FloatField(db_index=True, help_text='The recorded volume for the metric event.', null=True),
        ),
        migrations.AlterField(
            model_name='eat',
            name='time_stamp',
            field=models.DateTimeField(db_index=True, help_text='When the metric event occurred or began.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='time_stamp',
            field=models.DateTimeField(db_index=True, help_text='When the metric event occurred or began.'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='time_stamp',
            field=models.DateTimeField(db_index=True, help_text='When the metric event occurred or began.'),
        ),
        migrations.AlterField(
            model_name='note',
            name='time_stamp',
            field=models.DateTimeField(db_index=True, help_text='When the metric event occurred or began.'),
        ),
        migrations.AlterField(
            model_name='relax',
            name='time_stamp',
            field=models.DateTimeField(db_index=True, help_text='When the metric event occurred or began.'),
        ),
        migrations.AlterField(
            model_name='sex',
            name='time_stamp',
            field=models.DateTimeField(db_index=True, help_text='When the metric event occurred or began.'),
        ),
        migrations.AlterField(
            model_name='sleep',
            name='time_stamp',
            field=models.DateTimeField(db_index=True, help_text='When the metric event occurred or began.'),
        ),
    ]
